name: stt-dev
services:
  app:
    image: stt-dev:latest
    container_name: stt-dev
    build:
      target: dev
    volumes:
      # Bind-Mount local directories into the container for live code changes.
      - .:/app
      # Use a named volume to persist the venv and protect it from the workspace mount (pycharm).
      - venv:/app/.venv
      #- ./tests:/app/tests
      #- ./data:/app/data
      # 2. Use a named volume for node_modules for performance
      #  node-modules:/workspaces/my-project/node_modules
    ports:
      # Expose a port for a web server, API, etc  host:container
      - "8765:8765"
    # recommended to not use restart for dev
    # restart: unless-stopped

    user: appuser
    # Override the Dockerfile's CMD for development
    # This keeps the container running so IDE can attach
    command: sleep infinity

    # Define the named volume for the virtual environment
volumes:
  venv: