name: stt-dev
services:
  app:
    image: stt-dev:latest
    container_name: stt-dev
    build:
      target: dev
    volumes:
      # Mount local directories into the container for live code changes.
      - ./src:/app/src
      #- ./tests:/app/tests
      #- ./data:/app/data
    ports:
      # Expose a port for a web server, API, etc
      - "8765:8765"
    restart: unless-stopped